# Generated by Django 3.2.7 on 2022-01-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='close_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата устранения/внедрения'),
        ),
    ]
