# Generated by Django 3.2.7 on 2022-08-04 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0002_auto_20220803_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bug',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Замечание/предложение', 'verbose_name_plural': 'Замечания/предложения'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='bug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bugtracker.bug', verbose_name='Предложение/замечание'),
        ),
    ]
