repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: check-added-large-files
    - id: check-executables-have-shebangs
    - id: check-merge-conflict
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: no-commit-to-branch
      args: [--branch, main]

- repo: https://github.com/pycqa/flake8
  rev: 5.0.4
  hooks:
    - id: flake8

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      args: [--settings, setup.cfg]
