version: '3.8'

volumes:
  static_volume:
  media_volume:

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: >
      sh -c "python3 manage.py collectstatic --settings=ppr_project.settings.dev_docker &&
             python3 manage.py migrate --settings=ppr_project.settings.dev_docker &&
             python3 manage.py runserver 0.0.0.0:8000 --settings=ppr_project.settings.dev_docker"
    ports:
      - 8000:8000
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
    
  db:
    image: postgres:13.0-alpine
    env_file:
      - ./.env

