version: '3.8'

volumes:
  static_volume:
  media_volume:
  postgres_volume:

services:
  web:
    build: .
    restart: always
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - db
    env_file:
      - ppr_project/ppr_project/.env
    
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    env_file:
      - ppr_project/ppr_project/.env

  nginx:
    image: nginx:1.21.6-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
    depends_on:
      - web
