version: '3.8'

volumes:
  static_volume:
  media_volume:

networks:
  proxy_network:
    external: true
  default:
    driver: bridge

services:
  web:
    image: profcheg/ppr_project:latest
    command: >
      sh -c "python manage.py migrate &&
      python manage.py collectstatic --no-input --clear &&
      gunicorn ppr_project.wsgi:application --bind 0:8000"
    restart: always
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:13.0-alpine
    env_file:
      - ./.env

  nginx:
    container_name: kc
    image: nginx:1.21.6-alpine
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
    depends_on:
      - web
    networks:
      - proxy_network
      - default

  redis:
    image: redis:7.0.4-alpine

  celery:
    image: profcheg/ppr_project:latest
    command: sh -c "celery -A ppr_project worker --loglevel=INFO"
    restart: always
    depends_on:
      - web
      - redis
    env_file:
      - ./.env
