version: '3.8'

volumes:
  static_volume:
  media_volume:

services:
  web:
    image: profcheg/ppr_project:latest
    command: >
      sh -c "python manage.py migrate &&
      python manage.py collectstatic --no-input --clear &&
      gunicorn ppr_project.wsgi:application --bind 0:8000"
    restart: always
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:13.0-alpine
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.6-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - ./certbot/conf:/etc/letsencrypt/
      - ./certbot/www:/var/www/certbot/
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
    depends_on:
      - web

  certbot:
    profiles: ["certbot"]
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt/
      - ./certbot/www:/var/www/certbot/
    command: certonly --webroot -w /var/www/certbot --force-renewal --email pprofcheg@gmail.com -d ks-45.ru -d www.ks-45.ru --agree-tos --staging
    depends_on:
      - nginx

  redis:
    image: redis:7.0.4-alpine

  celery:
    image: profcheg/ppr_project:latest
    command: sh -c "celery -A ppr_project worker --loglevel=INFO"
    restart: always
    depends_on:
      - web
      - redis
    env_file:
      - ./.env
