version: '3.8'

volumes:
  static_volume:
  media_volume:

services:
  web:
    image: profcheg/ppr_project:latest
    command: sh -c "gunicorn ppr_project.wsgi:application --bind 0:8000"
    restart: always
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
    
  db:
    image: postgres:13.0-alpine
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.6-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
    depends_on:
      - web
