# Generated by Django 3.2.7 on 2021-10-13 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eq_type_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(max_length=10)),
                ('date_sheduled', models.DateField()),
                ('date_completed', models.DateField(auto_now_add=True)),
                ('employee1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee1', to='reports.employee')),
                ('employee2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee2', to='reports.employee')),
                ('employee3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee3', to='reports.employee')),
                ('equipment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_type', to='reports.equipmenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=20)),
                ('maintenance_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_category', to='reports.maintenancecategory')),
            ],
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_type', to='reports.facility'),
        ),
        migrations.CreateModel(
            name='EquipmentMaintenanceRegulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulations', models.TextField()),
                ('regulation_num', models.CharField(max_length=20)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_regulation', to='reports.equipment')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='reports.equipmenttype'),
        ),
    ]
