# Generated by Django 3.2.7 on 2021-11-24 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eqipment_type_name', models.CharField(max_length=30)),
                ('report_template', models.FilePathField(default='/')),
            ],
            options={
                'verbose_name': 'Тип оборудования',
                'verbose_name_plural': 'Типы оборудования',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Категория работ',
                'verbose_name_plural': 'Категории работ',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_type', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Тип ТО',
                'verbose_name_plural': 'Типы ТО',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sheduled', models.DateField()),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('access_journal_filled', models.BooleanField(default=False)),
                ('result_journal_filled', models.BooleanField(default=False)),
                ('employee1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee1_schedule', to='reports.employee')),
                ('employee2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee2_schedule', to='reports.employee')),
                ('employee3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee3_schedule', to='reports.employee')),
                ('equipment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_type_schedule', to='reports.equipmenttype')),
                ('maintenance_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_type', to='reports.maintenancetype')),
            ],
            options={
                'verbose_name': 'Планирование работ',
                'verbose_name_plural': 'Планирование работ',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=20)),
                ('maintenance_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.maintenancecategory')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.facility'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='maintenance_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.maintenancecategory'),
        ),
    ]
