# Generated by Django 3.2.7 on 2021-10-11 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shedule',
            new_name='Schedule',
        ),
        migrations.RemoveField(
            model_name='equipmenttype',
            name='maintenance_per_year',
        ),
    ]
