# Generated by Django 3.2.7 on 2021-12-01 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(max_length=25, verbose_name='Служба'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Фамилия И.О.'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=20, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='eqipment_type_name',
            field=models.CharField(max_length=30, verbose_name='Тип оборудования'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.facility', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='maintenance_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.maintenancecategory', verbose_name='Категория работ'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='report_template',
            field=models.FilePathField(default='/', verbose_name='Шаблон акта/протокола'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_name',
            field=models.CharField(max_length=20, verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='maintenance_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.maintenancecategory', verbose_name='Категория работ'),
        ),
        migrations.AlterField(
            model_name='maintenancecategory',
            name='category_name',
            field=models.CharField(max_length=25, verbose_name='Категория работ'),
        ),
        migrations.AlterField(
            model_name='maintenancetype',
            name='m_type',
            field=models.CharField(max_length=5, verbose_name='Тип ТО'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='access_journal_filled',
            field=models.BooleanField(default=False, verbose_name='Журнал допуска заполнен'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date_completed',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date_sheduled',
            field=models.DateField(verbose_name='Дата по плану'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='employee1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee1_schedule', to='reports.employee', verbose_name='Исполнитель #1'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='employee2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee2_schedule', to='reports.employee', verbose_name='Исполнитель #2'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='employee3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee3_schedule', to='reports.employee', verbose_name='Исполнитель #3'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='equipment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_type_schedule', to='reports.equipmenttype', verbose_name='Тип оборудования'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='maintenance_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_type', to='reports.maintenancetype', verbose_name='Тип ТО'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='result_journal_filled',
            field=models.BooleanField(default=False, verbose_name='Журнал ТО заполнен'),
        ),
    ]
