# Generated by Django 3.2.7 on 2021-10-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20211011_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancecategory',
            name='category_name',
            field=models.CharField(max_length=25),
        ),
    ]
