# Generated by Django 3.2.7 on 2021-09-28 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20210927_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.facility'),
        ),
    ]
