# Generated by Django 3.2.12 on 2022-02-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20220211_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(max_length=50, verbose_name='Служба'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Фамилия И.О.'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=50, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='eqipment_type_name',
            field=models.CharField(max_length=250, verbose_name='Тип оборудования'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_name',
            field=models.CharField(max_length=250, verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='maintenancecategory',
            name='category_name',
            field=models.CharField(max_length=50, verbose_name='Категория работ'),
        ),
        migrations.AlterField(
            model_name='maintenancetype',
            name='m_type',
            field=models.CharField(max_length=50, verbose_name='Тип ТО'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='template_name',
            field=models.CharField(max_length=250, verbose_name='Имя шаблона'),
        ),
    ]
