# Generated by Django 3.2.7 on 2022-03-10 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20220212_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporttemplate',
            name='equipment_type',
        ),
        migrations.RemoveField(
            model_name='reporttemplate',
            name='maintenance_type',
        ),
    ]
