# Generated by Django 3.2.7 on 2022-01-26 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_schedule_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100, verbose_name='Имя шаблона')),
                ('template', models.FilePathField()),
            ],
            options={
                'verbose_name': 'Шаблон акта/протокола',
                'verbose_name_plural': 'Шаблоны актов/протоколов',
            },
        ),
        migrations.RemoveField(
            model_name='equipmenttype',
            name='report_template',
        ),
        migrations.AddField(
            model_name='schedule',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_template', to='reports.reporttemplate', verbose_name='Шаблон акта/протокола'),
        ),
    ]
