# Generated by Django 3.2.7 on 2022-03-17 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20220310_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['department', 'name'], 'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
    ]
