# Generated by Django 3.2.7 on 2022-03-22 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_employee_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UncompleteReasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=250, verbose_name='Причина невыполнения')),
            ],
            options={
                'verbose_name': 'Причина невыполнения работ',
                'verbose_name_plural': 'Причины невыполнения работ',
            },
        ),
        migrations.AddField(
            model_name='historicalschedule',
            name='uncompleted',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reports.uncompletereasons', verbose_name='Причина невыполнения работы'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='uncompleted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_uncompleted_reason', to='reports.uncompletereasons', verbose_name='Причина невыполнения работы'),
        ),
    ]
