# Generated by Django 3.2.7 on 2022-01-26 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20220126_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='maintenance_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.maintenancetype', verbose_name='Тип ТО'),
        ),
    ]
