# Generated by Django 3.2.7 on 2022-01-26 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_reporttemplate_maintenance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='equipment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.equipmenttype', verbose_name='Тип оборудования'),
        ),
    ]
