# Generated by Django 3.2.7 on 2022-01-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_reporttemplate_equipment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo_approvals/%Y/%m/&d', verbose_name='Подтверждающее фото'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='template',
            field=models.FileField(upload_to='templates/'),
        ),
    ]
