# Generated by Django 3.2.7 on 2022-01-30 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0008_auto_20220130_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo_approvals/%Y/%m/%d', verbose_name='Подтверждающее фото'),
        ),
        migrations.CreateModel(
            name='HistoricalSchedule',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_sheduled', models.DateField(verbose_name='Дата по плану')),
                ('date_completed', models.DateField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('access_journal_filled', models.BooleanField(default=False, verbose_name='Журнал допуска заполнен')),
                ('result_journal_filled', models.BooleanField(default=False, verbose_name='Журнал ТО заполнен')),
                ('photo', models.TextField(blank=True, max_length=100, verbose_name='Подтверждающее фото')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('employee1', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reports.employee', verbose_name='Исполнитель #1')),
                ('employee2', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reports.employee', verbose_name='Исполнитель #2')),
                ('employee3', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reports.employee', verbose_name='Исполнитель #3')),
                ('equipment_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reports.equipmenttype', verbose_name='Тип оборудования')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('maintenance_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reports.maintenancetype', verbose_name='Тип ТО')),
                ('report', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reports.reporttemplate', verbose_name='Шаблон акта/протокола')),
            ],
            options={
                'verbose_name': 'historical Планирование работ',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
